name: Deploy to pre production

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: production
      url: https://test-vercel-pre-production.vercel.app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Download asset from a specific release version
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: "1.28.0.zip"

      - name: List Files
        run: ls -R

      - name: Unpack build archive
        run: |
          mkdir build && unzip 1.28.0.zip
          ls -R

      - name: List Files
        run: ls -R

      - name: Deploy project artifacts to Vercel
        run: vercel --prod --prebuilt .vercel --token=${{ secrets.VERCEL_TOKEN }}
